version: '3.7'

services:
  app:
    container_name: dressup_app
    image: dressup_app_image
    env_file:
      - .env.dressup
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./:/src
    network_mode: host
    ports:
      - 2811:2811

networks:
  default:
    external: true
    name: dressup_app_main
