version: '3.7'

services:
  app:
    container_name: dressup_app
    image: dressup_app_image
    env_file:
      - .env.example
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    container_name: dressup_postgres
    hostname: app_db
    image: postgres:14.1
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - app_pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  app_pg_data:
    driver: "local"

networks:
  default:
    external: true
    name: dressup_app_main
