version: '3.7'

services:
  app:
    container_name: dressup_app
    image: dressup_app_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - 8000:8000
    network_mode: host

volumes:
  app_pg_data:
    driver: "local"
