"""add_more_fields_to_user

Revision ID: a1c1a06d7d31
Revises: 000f493a2c78
Create Date: 2023-03-23 11:22:04.834076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a1c1a06d7d31"
down_revision = "000f493a2c78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("burst", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("waist", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("hip", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("weight", sa.Float(), nullable=True))
    op.add_column("user", sa.Column("height", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "height")
    op.drop_column("user", "weight")
    op.drop_column("user", "hip")
    op.drop_column("user", "waist")
    op.drop_column("user", "burst")
    # ### end Alembic commands ###
