"""add_styles_field

Revision ID: 26cd93bcbfc1
Revises: a1c1a06d7d31
Create Date: 2023-03-23 11:36:35.202066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "26cd93bcbfc1"
down_revision = "a1c1a06d7d31"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("styles", sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "styles")
    # ### end Alembic commands ###
