"""add_contact_model

Revision ID: c88b301a6a73
Revises: 3913b84b66ab
Create Date: 2023-06-08 14:40:00.174800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c88b301a6a73"
down_revision = "3913b84b66ab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("contact_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("contact_pkey")),
    )
    op.create_index(op.f("contact_user_id_idx"), "contact", ["user_id"], unique=False)
    op.create_unique_constraint(
        op.f("product_review_product_id_key"),
        "product_review",
        ["product_id", "user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("product_review_product_id_key"), "product_review", type_="unique"
    )
    op.drop_index(op.f("contact_user_id_idx"), table_name="contact")
    op.drop_table("contact")
    # ### end Alembic commands ###
