"""add_more_field_for_user

Revision ID: 000f493a2c78
Revises: ac55b4352a11
Create Date: 2023-03-22 03:51:27.797137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "000f493a2c78"
down_revision = "ac55b4352a11"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("last_name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("avatar_url", sa.String(), nullable=True))
    op.alter_column("user", "password", existing_type=postgresql.BYTEA(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "password", existing_type=postgresql.BYTEA(), nullable=False
    )
    op.drop_column("user", "avatar_url")
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
