"""add_product_rating_score

Revision ID: 825b66739435
Revises: 177cf327b079
Create Date: 2023-05-26 14:44:27.251518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "825b66739435"
down_revision = "177cf327b079"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product_rating", sa.Column("score", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_rating", "score")
    # ### end Alembic commands ###
