"""added_product_rating_unique_constraint

Revision ID: acf2fa2bcf67
Revises: 338bae562a5b
Create Date: 2023-05-26 10:48:50.456396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "acf2fa2bcf67"
down_revision = "338bae562a5b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("product_rating_product_id_key"),
        "product_rating",
        ["product_id", "user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("product_rating_product_id_key"), "product_rating", type_="unique"
    )
    # ### end Alembic commands ###
