"""added_product_hashtags

Revision ID: 3913b84b66ab
Revises: 825b66739435
Create Date: 2023-05-27 03:08:41.499103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3913b84b66ab"
down_revision = "825b66739435"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product", sa.Column("hashtags", sa.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "hashtags")
    # ### end Alembic commands ###
